name: Java CI with Maven

permissions:
  contents: write
on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Prepare Artifacts
      shell: bash
      run: |
        mv target/tronclass-java-1.0-SNAPSHOT.jar tronclass-java-${{ matrix.os }}.jar
        cp config.example.yaml config.yaml
        mkdir -p tessdata
        curl -L https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata -o tessdata/eng.traineddata
        jar -cMf tronclass-java-${{ matrix.os }}.zip tronclass-java-${{ matrix.os }}.jar config.yaml tessdata

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tronclass-java-${{ matrix.os }}-zip
        path: tronclass-java-${{ matrix.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find artifacts -name "*.zip" -exec mv {} . \;
          
          gh release create ${{ github.ref_name }} tronclass-java-ubuntu-latest.zip tronclass-java-windows-latest.zip \
            --target ${{ github.sha }} \
            --title "TronClass Auto Rollcall ${{ github.ref_name }}" \
            --notes "gen from ${GITHUB_SHA:0:7}. Ubuntu and Windows jar with tessdata." \
            --generate-notes
